import { ApiProperty } from '@nestjs/swagger';
import {
  IsBoolean,
  IsIn,
  IsInt,
  IsOptional,
  IsString,
  IsUUID,
  Max,
  MaxLength,
  Min,
  MinLength,
} from 'class-validator';
import type {
  ImageAspectRatio,
  ImageModel,
  ImageStyle,
} from '../providers/image-provider.interface';

export const IMAGE_STYLES = [
  'realistic',
  'illustration',
  '3d',
  'minimalist',
  'infographic',
  'mkt-brand',
] as const;

export const IMAGE_RATIOS = ['16:9', '4:3', '1:1'] as const;
export const IMAGE_MODELS = ['flux-schnell', 'dalle-3'] as const;

/** Section 8 TN6 `/generate` body. */
export class GenerateImageDto {
  @ApiProperty({
    example: 'SEO local cho doanh nghiệp nhỏ — minh hoạ map pack',
    minLength: 5,
    maxLength: 1000,
  })
  @IsString()
  @MinLength(5)
  @MaxLength(1000)
  prompt!: string;

  @ApiProperty({ required: false, enum: IMAGE_STYLES, default: 'mkt-brand' })
  @IsOptional()
  @IsIn(IMAGE_STYLES as unknown as string[])
  style?: ImageStyle;

  @ApiProperty({ required: false, enum: IMAGE_RATIOS, default: '16:9' })
  @IsOptional()
  @IsIn(IMAGE_RATIOS as unknown as string[])
  aspect_ratio?: ImageAspectRatio;

  @ApiProperty({ required: false, minimum: 1, maximum: 4, default: 1 })
  @IsOptional()
  @IsInt()
  @Min(1)
  @Max(4)
  count?: number;

  @ApiProperty({ required: false, enum: IMAGE_MODELS, default: 'flux-schnell' })
  @IsOptional()
  @IsIn(IMAGE_MODELS as unknown as string[])
  model?: ImageModel;

  @ApiProperty({ required: false, description: 'Attach to this article id.' })
  @IsOptional()
  @IsUUID()
  article_id?: string;

  @ApiProperty({
    required: false,
    description: 'Override the autogenerated alt text with this exact value.',
  })
  @IsOptional()
  @IsString()
  @MaxLength(500)
  alt_text?: string;
}

/** Section 8 TN6 `/generate-for-article` body. */
export class GenerateForArticleDto {
  @ApiProperty()
  @IsUUID()
  article_id!: string;

  @ApiProperty({ required: false, default: true })
  @IsOptional()
  @IsBoolean()
  include_featured?: boolean;

  @ApiProperty({ required: false, enum: IMAGE_STYLES, default: 'mkt-brand' })
  @IsOptional()
  @IsIn(IMAGE_STYLES as unknown as string[])
  style?: ImageStyle;

  @ApiProperty({ required: false, enum: IMAGE_MODELS, default: 'flux-schnell' })
  @IsOptional()
  @IsIn(IMAGE_MODELS as unknown as string[])
  model?: ImageModel;

  @ApiProperty({
    required: false,
    default: 4,
    minimum: 1,
    maximum: 8,
    description: 'Max in-content images (one per H2). Featured is separate.',
  })
  @IsOptional()
  @IsInt()
  @Min(1)
  @Max(8)
  max_in_content?: number;
}
